--- vulnerable_linux_driver/Makefile	2023-03-06 17:05:13
+++ vulnerable_linux_driver_patched/Makefile	2023-01-24 09:34:28
@@ -2,7 +2,7 @@
 
 EXTRA_CFLAGS += -fno-stack-protector
 all:
-	make -C /lib/modules/`uname -r`/build M=$(PWD) modules
+	make -C /lib/modules/5.10.0-21-amd64/build M=$(PWD) modules
 clean:
 	rm -rf src/*.ko
 	rm -rf src/*.mod
